@startuml ComisionService
interface ComisionService {
 + listAll(): Iterable<Comision>
 + getById(id: int): Comision
 + save(comision: Comision): Comision
 + save(comisiones: List<Comision>): void
 + delete(id: int): void
}
ComisionService <|.. ComisionServiceImpl
@enduml