@startuml SectorService
interface SectorService {
 + listAll(): Iterable<Sector>
 + listActive(): Iterable<Sector>
 + getById(id: int): Sector
 + save(sector: Sector): Sector
 + save(sectores: List<Sector>): void
 + delete(id: int): void
}
SectorService <|.. SectorServiceImpl
@enduml