@startuml TramiteAutorizadoService
interface TramiteAutorizadoService {
 + listAll(): Iterable<TramiteAutorizado>
 + getById(id: TramiteAutorizadoKey): TramiteAutorizado
 + save(tramiteAutorizado: TramiteAutorizado): TramiteAutorizado
 + save(tramiteAutorizados: List<TramiteAutorizado>): void
 + delete(id: TramiteAutorizadoKey): void
 + deleteByIdAutorizadoId(id: int): void
}
TramiteAutorizadoService <|.. TramiteAutorizadoServiceImpl
@enduml