@startuml TramiteService
interface TramiteService {
 + listAll(): Iterable<Tramite>
 + listBySectorActual(sectorActual: Sector): List<Autorizado>
 + listByEstado(estado: EstadoTramite): List<Tramite>
 + getById(id: int) : Tramite
 + save(tramite: Tramite): Tramite
 + save(tramites: List<Tramite>): void
 + delete(id: int) : void
}
TramiteService <|.. TramiteServiceImpl
@enduml