@startuml ComisionController
class ComisionController {
 - comisionService: ComisionService
 - <<final>> logger: Logger
 + setComisionService(comisionService: ComisionService): void
 + list(model: Model): ResponseEntity
 + showComision(id: int, model: Model): ResponseEntity
 + saveComision(comision: Comision): ResponseEntity
 + updateComision(id: int, comision: Comision): ResponseEntity
 + delete(id: int): ResponseEntity
}
@enduml