@startuml SectorController
class SectorController {
 - sectorService: SectorService
 - <<final>> logger: Logger
 + setSectorService(sectorService: SectorService): void
 + list(req: HttpServletRequest, activo: boolean): ResponseEntity
 + showSector(id: int, model: Model): ResponseEntity
 + saveSector(sector: Sector): ResponseEntity
 + updateSector(id: int, sector: Sector): ResponseEntity
 + deleteSector(id: int): ResponseEntity
}
@enduml