@startuml EstadoTramite

class EstadoTramite{
 -id: int
 -nombre: String
 -descripcion: String
 -usuAlta: String
 -fechaAlta: Date
 -usuModif: String
 -fechaModif: Date
 +getters()
 +setters()
}

@enduml