@startuml Sector

class Sector{
 -id: int
 -canal: String
 -sector: String
 -descripcion: String
 -activo: boolean
 -usuAlta: String
 -fechaAlta: Date
 -usuModif: String
 -fechaModif: Date
 +getters()
 +setters()
}

@enduml