@startuml TipoTramiteCampoKey

class TipoTramiteCampoKey{
 -tipoTramiteId: int
 -campoDisponibleId: int
 +TipoTramiteCampo(): TipoTramiteCampoKey
 +TipoTramiteCampo(tipoTramiteId: int, campoDisponibleId: int): TipoTramiteCampoKey
 +getters()
 +setters()
}

@enduml