@startuml TipoTramite

class TipoTramite{
 -id: int
 -descripcion: String
 -cobraComision: boolean
 -comision: Comision
 -requiereDocumentacion: boolean
 -activo: boolean
 -autorizado: boolean
 -sectorInicial: SectorInicial
 -campos: Set<TipoTramiteCampo>
 -horasResolucion: Long
 -horasVencimiento: Long
 -usuAlta: String
 -fechaAlta: Date
 -usuModif: String
 -fechaModif: Date
 +getters()
 +setters()
}

@enduml