@startuml Tramite

class Tramite{
 -id: int
 -tipoTramite: TipoTramite
 -clienteId: int
 -autorizado: Set<TramiteAutorizado>
 -sectorinicio: Sector
 -sectorActual: Sector
 -detalle: Set<TramiteDetalle>
 -cuentaCobro: String
 -estado: EstadoTramite
 -fechaFinalizacion: Date
 -fechaInicio: Date
 -fechaVencimiento: Date
 -usuAlta: String
 -fechaAlta: Date
 -usuModif: String
 -fechaModif: Date
 +getters()
 +setters()
}

@enduml