@startuml EstadoTramiteServiceImpl

class EstadoTramiteServiceImpl{
 - <<final>> logger: Logger
 - estadoTramiteRepository: EstadoTramiteRepository
 + setRepository(estadoTramiteRepository: EstadoTramiteRepository): void
 + listAll(): Iterable<EstadoTramite>
 + getById(id: int): EstadoTramite
 + save(estadoTramite: EstadoTramite): EstadoTramite
 + save(estadoTramite: List<EstadoTramite>): void
 + delete(id: int): void
}

@enduml