@startuml architecture_services

title GOT - Services Architecture

rectangle "Gestion Online de Tramites - API Services" {
  rectangle "Java" as java {
    rectangle "Spring boot Framework" as spring {
        [Services API RestFUL ] as rest_service
        [Controllers] as controllers_service
        [Models] as models_service
        [Services] as service_service
        [Repositories] as dao_service
    }
    rectangle "JPA Framework" as hibernate {
      [JPA classes] as hibernate_class
    }    
  }
}

rectangle "GOT DataBase" {
  rectangle "Relational Database" as oracle {
    [Model] as model_db
  }
}

[dao_service] <--> [hibernate_class]
[hibernate_class] <--> [model_db]

@enduml