@startuml CampoDisponibleServiceImpl

class CampoDisponibleServiceImpl{
 - <<final>> logger: Logger
 - campoDisponibleRepository: CampoDisponibleRepository
 + setRepository(campoDisponibleRepository: CampoDisponibleRepository): void
 + listAll(): Iterable<CampoDisponible>
 + getById(id: int): CampoDisponible
 + save(campoDisponible: CampoDisponible): Autorizado
 + save(campoDisponible: List<CampoDisponible>): void
 + delete(id: int): void
}

@enduml