@startuml ComisionServiceImpl

class ComisionServiceImpl{
 - <<final>> logger: Logger
 - comisionRepository: ComisionRepository
 + setRepository(comisionRepository: ComisionRepository): void
 + listAll(): Iterable<Comision>
 + getById(id: int): Comision
 + save(comision: Comision): Comision
 + save(comision: List<Comision>): void
 + delete(id: int): void
}

@enduml