@startuml TramiteDetalleServiceImpl

class TramiteDetalleServiceImpl{
 -<<final>> logger: Logger
 -tramiteDetalleRepository: TramiteDetalleRepository
 +setRepository(tramiteDetalleRepository: TramiteDetalleRepository): void
 +listAll(): Iterable<TramiteDetalle>
 +getById(id: TramiteDetalleKey): TramiteDetalle
 +save(tramiteDetalle: TramiteDetalle): TramiteDetalle
 +save(tramiteDetalle: List<TramiteDetalle>): void
 +delete(id: TramiteDetalleKey): void
}

@enduml