@startuml interfaces

'Components
!include ./repository/autorizadoRepository.wsd
!include ./repository/campoDisponibleRepository.wsd
!include ./repository/comisionRepository.wsd
!include ./repository/estadoTramiteRepository.wsd
!include ./repository/sectorRepository.wsd
!include ./repository/tipoTramiteCampoRepository.wsd
!include ./repository/tipoTramiteRepository.wsd
!include ./repository/tramiteAutorizadoRepository.wsd
!include ./repository/tramiteDetalleRepository.wsd
!include ./repository/tramiteRepository.wsd
!include ./service/autorizadoService.wsd

@enduml
!include ./service/autorizadoService.wsd
!include ./service/campoDisponibleService.wsd
!include ./service/comisionService.wsd
!include ./service/estadoTramiteService.wsd
!include ./service/sectorService.wsd
!include ./service/tipoTramiteCampoService.wsd
!include ./service/tipoTramiteService.wsd
!include ./service/tramiteAutorizadoService.wsd
!include ./service/tramiteDetalleService.wsd
!include ./service/tramiteService.wsd